AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-events-otel

  Sample SAM Template for aws-events-otel

Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  EventsApi:
    Type: AWS::AppSync::Api
    Properties:
      Name: "FlightStatus"
      EventConfig:
        AuthProviders:
          - AuthType: API_KEY
        ConnectionAuthModes:
          - AuthType: API_KEY
        DefaultPublishAuthModes:
          - AuthType: API_KEY
        DefaultSubscribeAuthModes:
          - AuthType: API_KEY
  
  FlightsNamespace:
    Type: AWS::AppSync::ChannelNamespace
    Properties:
      ApiId: !GetAtt EventsApi.ApiId
      Name: flights

  SeatAssignmentNamespace:
    Type: AWS::AppSync::ChannelNamespace
    Properties:
      ApiId: !GetAtt EventsApi.ApiId
      Name: seats

  FlightStatusApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt EventsApi.ApiId
      
  # HelloWorldFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: hello-world/
  #     Handler: app.lambdaHandler
  #     Runtime: nodejs22.x
  #     Architectures:
  #     - x86_64
  #     Events:
  #       HelloWorld:
  #         Type: Api
  #         Properties:
  #           Path: /hello
  #           Method: get
  #   Metadata:
  #     BuildMethod: esbuild
  #     BuildProperties:
  #       Minify: true
  #       Target: es2020
  #       Sourcemap: true
  #       EntryPoints:
  #       - app.ts

Outputs:
  Endpoint:
    Description: AppSync Events endpoint
    Value: !Sub "https://${EventsApi.Dns.Http}/event"