receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  awsxray:
    region: ${AWS_REGION}
  awsemf:
    region: ${AWS_REGION}
  awscloudwatchlogs:
    region: ${AWS_REGION}
    log_group_name: "/aws/observability-demo"
    log_stream_name: "application-logs"

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777

service:
  extensions: [health_check, pprof]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsemf, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [awscloudwatchlogs, debug]